default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>


test:
  <<: *default
  database: hello_rails_react
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
# As with config/credentials.yml, you never want to store sensitive information,
#
production:
  <<: *default
  database: hello_rails_react_production
  username: hello_rails_react
  password: <%= ENV["MYBUDGETAPP_DATABASE_PASSWORD"] %>
